### ISSUE TITLE
feat: PAR should acknowledge valid mentions

### ISSUE THREAD

**Issue by orimdominic** [sudo-kaizen/pick-at-random#19]
### Summary

PAR should reply to commands that are cancellation requests and pick commands after persisting them

### Basic example

A user who makes a cancel request for a pick command should receive a reply to the tweet, acknowledging that it has been cancelled

### Tasks

- [x] Implement ability to reply
- [x] Reply pick command mention
- [ ] Like cancel mention

### Motivation

Users should get feed back for actions carried out. It makes for better UX.

**Comment by orimdominic** [comment]
The reply to feedback functionality has been removed to prevent the bot from maxing out Twitter limits

**Comment by orimdominic** [comment]
Associated with #48
